### ISSUE TITLE
mcrypt is deprecated

### ISSUE THREAD

**Issue by tonyguesswho** [blockavel/lara-block-io#37]
i use php 7.1.1 and mcrypt is deprecated in my php version.Is there any way around it in other to enable me access the withdraw method.

**Comment by alejandro-carstens** [comment]
As you very well pointed out, mcrypt has been deprecated in php7.1. The only solutions to resolve this issues would be to move down to php7.0. If that is an option for you. I will go ahead and close the issue, since solving it is not within this repository control. I will be adding a note in the readme, so thanks for pointing this issue out. Cheers and the best of luck.
